const cookies = [
  {
    domain: ".linkedin.com",
    expirationDate: 1660342003.467088,
    hostOnly: false,
    httpOnly: false,
    name: "__ssid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "60ceae4b-4e38-457a-a629-7b0340035858",
    id: 1,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1652801713,
    hostOnly: false,
    httpOnly: false,
    name: "_gcl_au",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1.1.1871281891.1636544504",
    id: 2,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1645457547.905014,
    hostOnly: false,
    httpOnly: false,
    name: "_guid",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "8526cd2d-ceaf-466f-9bd4-b43bb63b2b0e",
    id: 3,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660578260,
    hostOnly: false,
    httpOnly: false,
    name: "AMCV_14215E3D5995C57C0A495C55%40AdobeOrg",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "-637568504%7CMCIDTS%7C19039%7CMCMID%7C33307845254433757334677520206068160348%7CMCOPTOUT-1645033460s%7CNONE%7CvVersion%7C5.1.1",
    id: 4,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "1",
    id: 5,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1647381981.523066,
    hostOnly: false,
    httpOnly: false,
    name: "AnalyticsSyncHistory",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQJoTRk-9S9KWgAAAX71H2GdFZ7zgomFE2YXPIf6suHs90qea5TeVm7FfZLz6GCea2ggOFpiaHzaNy-KpW7aNw",
    id: 6,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1649592634.451302,
    hostOnly: false,
    httpOnly: false,
    name: "bcookie",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: '"v=2&1d33d810-3049-4b48-894b-8b86663e5164"',
    id: 7,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660342005.633583,
    hostOnly: false,
    httpOnly: true,
    name: "dfpfpt",
    path: "/",
    sameSite: "lax",
    secure: true,
    session: false,
    storeId: "0",
    value: "9894f6bb13a04bd7b6cdb7763fdc63b2",
    id: 8,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: true,
    name: "fptctx2",
    path: "/",
    sameSite: "lax",
    secure: true,
    session: true,
    storeId: "0",
    value:
      "taBcrIH61PuCVH7eNCyH0AEX4aYkgtBfv7X8PIbvtOCMkwFL%252bSid3xgpK91Fnnfi1gip0EpUvMhHw64%252fNVjBelUirp6saLLbwHylhIBjmJts3uFFAWx14xC9r3UvCJ6BBjLXaefWelybLaB%252bwriN77LBPRWk1x%252fbfRng%252b4kQk%252f9kJPlURazJCjM3zNixPmMxAssoqwAXZZQoln3LFme3W0Kuel1Bc9jizZHgaJSToj8AR68AldasjMjuKTJZAIQtIibVXzJJfwsVTOm8VYgirEHuM9kk6ezHTto4jkGTIvdK0iC3Y%252bNfQdyMaTv4PkFh",
    id: 9,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660578260,
    hostOnly: false,
    httpOnly: false,
    name: "gpv_pn",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "www.linkedin.com%2Flearning%2Flearning-docker-2018%2Fwhy-create-containers-using-docker",
    id: 10,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "lang",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: true,
    storeId: "0",
    value: "v=2&lang=en-us",
    id: 11,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660483799.321227,
    hostOnly: false,
    httpOnly: false,
    name: "li_mc",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "MTsyMTsxNjQ0OTMxNzk5OzE7MDIxLi/UECQF9pRDjqZyRjdWZwmNUvAZxpVPdC1mKUwGNh4=",
    id: 12,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1652708003.157195,
    hostOnly: false,
    httpOnly: false,
    name: "li_sugr",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "95ac968e-9a69-459d-a78c-98e270ddfc47",
    id: 13,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660484084.190377,
    hostOnly: false,
    httpOnly: false,
    name: "liap",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "true",
    id: 14,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1645112065.309096,
    hostOnly: false,
    httpOnly: false,
    name: "lidc",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      '"b=VGST02:s=V:r=V:a=V:p=V:g=2530:u=1:x=1:i=1645025664:t=1645112064:v=2:sig=AQGsf9qe21WIBrniXENK3-Ly0xD5fKfv"',
    id: 15,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1647381981.794909,
    hostOnly: false,
    httpOnly: false,
    name: "lms_ads",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQG_jBulLxaUOAAAAX71H2KmDbaW-M8uAylsgWlnmufdRM-C4-ROVmLZ4uzk3GtYeG1VY8iJ792RPHRjB3aT1X94s5oPecLb",
    id: 16,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1647381981.795124,
    hostOnly: false,
    httpOnly: false,
    name: "lms_analytics",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQG_jBulLxaUOAAAAX71H2KmDbaW-M8uAylsgWlnmufdRM-C4-ROVmLZ4uzk3GtYeG1VY8iJ792RPHRjB3aT1X94s5oPecLb",
    id: 17,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_cc",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "true",
    id: 18,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1657140923,
    hostOnly: false,
    httpOnly: false,
    name: "s_fid",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "2E7987106525209F-1A8F89AD9FE2A5EA",
    id: 19,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_ips",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "933",
    id: 20,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_plt",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "2.93",
    id: 21,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_pltp",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "www.linkedin.com%2Flearning%2F",
    id: 22,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_ppv",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value:
      "www.linkedin.com%2Flearning%2Flearning-docker-2018%2Fwhy-create-containers-using-docker%2C100%2C100%2C933%2C1%2C1",
    id: 23,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_sq",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "%5B%5BB%5D%5D",
    id: 24,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "s_tp",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "933",
    id: 25,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1660578260,
    hostOnly: false,
    httpOnly: false,
    name: "s_tslv",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "1645026260264",
    id: 26,
  },
  {
    domain: ".linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "sdsc",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: true,
    storeId: "0",
    value: "22%3A1%2C1644931983997%7ECONN%2C0gFvKmNA%2BLd17kq5TvietyE1lhB8%3D",
    id: 27,
  },
  {
    domain: ".linkedin.com",
    expirationDate: 1647524002,
    hostOnly: false,
    httpOnly: false,
    name: "UserMatchHistory",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQIVwl1yAwoZ9gAAAX79lnVIps9_Pkx0sMrfweLKLjxqe1k7Spjs87qSvU2BUHkDHup6ROVL2pYSnon7nbzkbCoW6b_KQqoqfnVl_vfDI9St-0hn7Qhx2f5KjP35VMGvplAAsIn4CebFwjetKwldTOjvudu194hSRJUTZe7XGvmTmRw0nAIhFZBYo6bGu-4x51zTGgTTqaQbkgThjMhsy8oaIcpIxFKj5KAifBoHUdlLe0PaCnyLcNA74rseNAJY9Wdn94c5AxWk3t2IC9cfhrJx1oFIpN7BJceGnLo",
    id: 28,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1649592634.451338,
    hostOnly: false,
    httpOnly: true,
    name: "bscookie",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      '"v=1&2021101212103239c867a3-12ee-4628-84d5-5bb493210cb9AQGaW_LjfYsrl7FyKUwzYWxRozPN7QHL"',
    id: 29,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1652707798.93205,
    hostOnly: false,
    httpOnly: false,
    name: "JSESSIONID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: '"ajax:8354134475605925388"',
    id: 30,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1660484084.190086,
    hostOnly: false,
    httpOnly: true,
    name: "li_at",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQEGAGMBAAAAAAcgu9YAAAF-_Zey2AAAAX8hpDbYTQAARnVybjpsaTplbnRlcnByaXNlUHJvZmlsZToodXJuOmxpOmVudGVycHJpc2VBY2NvdW50Ojk1MjMxNDczLDE1NjY1ODYxNCnKkXZ4VYbaniq96zWfF1N7hoBhBz-8Ops3OOr7I-WDkYX-Fk5XmXOV_BOrNU3wLfCe8vM4J-zbLX7JLvhFQHatHpFWPS07q30AriZbfYhdeslhmio",
    id: 31,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1660484084.190764,
    hostOnly: false,
    httpOnly: true,
    name: "li_ep_auth_context",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AFBhcHA9bGVhcm5pbmcsYWlkPTk1MjMxNDczLGlpZD0xMTEyMjQ0MTcscGlkPTE1NjY1ODYxNCxleHA9MTY1MDExNjA4NDQ2MyxjdXI9dHJ1ZQHYAMOmxRRCqMFjJLYE9DBl3om_sQ",
    id: 32,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1660483798.931265,
    hostOnly: false,
    httpOnly: true,
    name: "li_rm",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AQFI1XYaKFBnsgAAAXx0a1spLVX4tvFQTdbOsNMo2S_K4p4gDjsGSgDxcm328q7aTykReCZOtTgv0qaG05zOeC68LNL7XToyDmquIDRONYVoXYlfaLZj_BZF",
    id: 33,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1660484001,
    hostOnly: false,
    httpOnly: false,
    name: "li_theme",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "light",
    id: 34,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1660484001,
    hostOnly: false,
    httpOnly: false,
    name: "li_theme_set",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "app",
    id: 35,
  },
  {
    domain: ".www.linkedin.com",
    hostOnly: false,
    httpOnly: false,
    name: "spectroscopyId",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: true,
    storeId: "0",
    value: "9a75992c-ff90-433c-bded-477c427ae846",
    id: 36,
  },
  {
    domain: ".www.linkedin.com",
    expirationDate: 1646141601,
    hostOnly: false,
    httpOnly: false,
    name: "timezone",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "Africa/Casablanca",
    id: 37,
  },
  {
    domain: "www.linkedin.com",
    expirationDate: 1660483798,
    hostOnly: true,
    httpOnly: false,
    name: "g_state",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: '{"i_l":0}',
    id: 38,
  },
  {
    domain: "www.linkedin.com",
    hostOnly: true,
    httpOnly: false,
    name: "lil-lang",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: true,
    storeId: "0",
    value: "en_US",
    id: 39,
  },
  {
    domain: "www.linkedin.com",
    hostOnly: true,
    httpOnly: false,
    name: "PLAY_LANG",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "en",
    id: 40,
  },
  {
    domain: "www.linkedin.com",
    hostOnly: true,
    httpOnly: true,
    name: "PLAY_SESSION",
    path: "/",
    sameSite: "lax",
    secure: true,
    session: true,
    storeId: "0",
    value:
      "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InNlc3Npb25faWQiOiJkMGIzZWIwOC0wNmM2LTRkYTItYjFhOS1kYThiMzgzYzdhN2R8MTY0NDUwNzA3NyIsImFsbG93bGlzdCI6Int9IiwicmVjZW50bHktc2VhcmNoZWQiOiIiLCJyZWZlcnJhbC11cmwiOiJodHRwczovL3d3dy5saW5rZWRpbi5jb20vcHJlbWl1bS9wcm9kdWN0cy8_ZmFtaWx5PWpzcyZtaWRUb2tlbj1BUUZNOVlRQXNvR0ozUSZtaWRTaWc9MUZJWFg1NDlzUlRxNDEmdHJrPWVtbC1lbWFpbF9qb2JfYWxlcnRfZGlnZXN0XzAxLWpvYl9hbGVydC0xMi1wcmVtaXVtX3Vwc2VsbF90b3BfYXBwbGljYW50X21lcmNhZG8mdHJrRW1haWw9ZW1sLWVtYWlsX2pvYl9hbGVydF9kaWdlc3RfMDEtam9iX2FsZXJ0LTEyLXByZW1pdW1fdXBzZWxsX3RvcF9hcHBsaWNhbnRfbWVyY2Fkby1udWxsLThyM21oYiU3RWt5dTBkejBqJTdFZnItbnVsbC1uZXB0dW5lJTJGcHJlbWl1bSUyRXByb2R1Y3RzIiwiUk5ULWlkIjoifDAiLCJyZWNlbnRseS12aWV3ZWQiOiIiLCJDUFQtaWQiOiLClTdWwojCjcKHSS3Cklx1MDAxQirCulNYwotVIiwiZXhwZXJpZW5jZSI6IiIsInRyayI6IiJ9LCJuYmYiOjE2NDQ1MDcwNzcsImlhdCI6MTY0NDUwNzA3N30.Wq6wATsIk2MzOhaPqGtDqj9rfqOcTAn1wh7DfL3kXcU",
    id: 41,
  },
  {
    domain: "www.linkedin.com",
    expirationDate: 1658580756.45272,
    hostOnly: true,
    httpOnly: false,
    name: "visit",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "v=1&M",
    id: 42,
  },
];

module.exports = cookies;
